exercise01/exe01/urls.py
from django.conf.urls import url
from exe01 import views

app_name = 'exe01'

urlpatterns = [
    url(r'^apps/$',views.apps, name = 'apps'),
    url('registration/',views.registration, name = 'registration'),
    url(r'^users/',views.users_ls, name = 'users'),
    url(r'^login/',views.user_login, name = 'user_login'),
]

exercise01/exercise01/urls.py
from django.contrib import admin
from django.urls import path
from exe01 import views
from django.conf.urls import url, include
#from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^exe01/', include('exe01.urls')),
    url(r'^logout/',views.user_logout, name= 'logout'),
    url(r'^special/',views.special, name= 'special'),
    #path('change-password/', auth_views.PasswordChangeView.as_view()),
    url(r'^',views.index, name = 'index'),
]

exercise01/exe01/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

exercise01/exe01/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators
from exe01.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

exercise01/exe01/views.py
from django.shortcuts import render
from exe01.forms import UserProfileInfoForm, UserForm
from exe01.models import UserProfileInfo
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage

# funzioni per il processo login
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from exe01.funzioni import raddoppio, import_file, normaliz_path



# Create your views here.


def index(request):
    return render(request, 'index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required(login_url='/exe01/login/')
def special(request):
    return HttpResponse('You are logged in, Nice!')


def registration(request):

    registered = False


    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)


        if user_form.is_valid() and profile_form.is_valid():
            # Do Something

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
            print(registered)

        else:
            print(user_form.errors,profile_form.errors )

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'folder01/registration.html', {'user_form': user_form, 'profile_form' : profile_form, 'registered' : registered} )



def users_ls(request):

    myhelp_dict = {}
    #users_list = User.objects.order_by('user_id')
    users_list = User.objects.values()
    users_list = [entry for entry in users_list]
    for items in users_list:
        for item in items:
            print(item, ': ', items[item] )

    myhelp_dict['users_list'] = users_list
    return render(request, 'folder01/users.html', context = myhelp_dict )


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)


        if user is not None:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print('Someone tried to login and failed!')
            print('Username: {} and password {}'.format(username,password))
            return HttpResponse("invalid login detail supplied!")
    else:
        return render(request, 'folder01/login.html', {})

"""
def apps(request):

    num = raddoppio(5)

    return render(request, 'folder01/apps.html', {'num' : num, 'test' : settings.MEDIA_DIR })


"""
def apps(request):

    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        file_ex = import_file(normaliz_path(uploaded_file_url))
        return render(request, 'folder01/apps.html', {
            'uploaded_file_url': uploaded_file_url, 'file_ex' : file_ex
        })



    return render(request, 'folder01/apps.html', {})

exercise01/templates/folder01/apps.html
<!DOCTYPE html>
{% extends 'folder01/base.html' %}

{% block body_block%}

<!-- <h1>WELCOME RELATIVE URL TEMPLATES</h1> -->

<div class="container">
  <div class="row">
    <div id="guest-map" class="jumbotron col-sm text-center" style="background-color: #6C5CFF">
      <h3>APP ONE</h3>
    </div>
    <div id="mysql-int" class="jumbotron col-sm text-center" style="background-color: #FF5C5C">
      <h3>APP TWO</h3>
    </div>
    <div id="todolist" class="jumbotron col-sm text-center" style="background-color: #7FFF5C">
      <h3>APP THREE</h3>
    </div>
  </div>
</div>

<div class="container">
  <div class="jumbotron">

    <p>
      {{ test }}
    </p>
    <h3>Selezionare il file:</h3>

    <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- {{user_form.as_p}}
      {{profile_form.as_p}} -->
      <input type="file" name="myfile">
      <input type="submit" class="btn btn-primary" name="" value="Upload">
    </form>

    {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    {% endif %}

    {% for item in file_ex %}
    <p>{{ item }}</p>
    {% endfor%}


  </div>

</div>


{% endblock %}

exercise01/templates/folder01/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static "css/mystyle.css"%}">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'exe01:registration' %}">Registration</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'exe01:apps' %}">Apps</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'exe01:users' %}">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'exe01:user_login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

<div class="container">

  {% block body_block%}

  {% endblock %}

</div>

</body>

</html>

exercise01/templates/folder01/login.html
{% extends 'folder01/base.html' %}

{% block body_block %}

<h1>Please Login</h1>
<form  action="{% url 'exe01:user_login' %}" method="post">
  {% csrf_token %}
  <label for="username">Username:</label>
  <input type="text" name="username" placeholder="Enter your username">
  <label for="password">Password:</label>
  <input type="password" name="password" placeholder="Enter your password">
  <input type="submit" class="btn btn-primary" name="" value="Login">

{% endblock %}

exercise01/templates/folder01/registration.html
{% extends 'folder01/base.html' %}

{% block body_block %}

<div class="container">
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for resistering</h1>
    {% else %}
      <h1>Register here</h1>
      <h3>Fill out the form:</h3>

      <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input type="submit" class="btn btn-primary" name="" value="Register">
      </form>
    {% endif %}
  </div>
</div>
{% endblock %}

</body>

</html>

exercise01/templates/folder01/users.html
{% extends 'folder01/base.html' %}

{% load static %}




{% block body_block %}


<div class="jumbotron">
  <table>

    <tr>
      <th>KEY</th>
      <th>VALUE</th>
    </tr>

    {% if users_list %}

      {% for data in users_list %}

        {% for key,value in data.items %}
        <tr>
          <td>{{ key }}</td>
          <td>{{ value }}</td>
        </tr>
        {% endfor %}

      {% endfor %}
    {% endif %}
  </table>
</div>
{% endblock %}

</body>

</html>

exercise01/templates/index.html
<!DOCTYPE html>
{% extends 'folder01/base.html' %}
{% load my_extras %}


{% block body_block%}
<h1>WELCOME HOME</h1>

<h1>{{ text|taglio:"Home" }}</h1>
<h1>{{ text|grassetto }}</h1>
<h1>{{ number|add:"99" }}</h1>



{% endblock %}